CREATE TABLE state (
    id BIGINT NOT NULL AUTO_INCREMENT,
    country_id BIGINT NOT NULL,
    DESCRIPTION MEDIUMTEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (country_id) REFERENCES country(id));
    
    CREATE TABLE city (
    id BIGINT NOT NULL AUTO_INCREMENT,
    state_id BIGINT NOT NULL,
    DESCRIPTION MEDIUMTEXT,
    PRIMARY KEY (id),
    FOREIGN KEY (state_id) REFERENCES state(id));

CREATE TABLE country(
id BIGINT NOT NULL AUTO_INCREMENT,
DESCRIPTION MEDIUMTEXT,
PRIMARY KEY (id))